### ISSUE TITLE
WARNING: Can not find data for scan 99 window 0 feed 11 polarization 0

### ISSUE THREAD

**Issue by aakepley** [low-sky/degas#13] opened 2017-02-23 16:29 UTC
I keep getting the message at the beginning of when degas.calscans() starts processing a group of feeds.
e.g.

```
sdfitsDataDir = '/home/sdfits'
project = 'AGBT17A_304'
session = '01'
galaxy = 'ngc4321'
line = 'hcn'

dataFileName = sdfitsDataDir+"/"+project+'_'+session +'/' + project+'_'+session+'.raw.vegas'

dataOutDir = "./"+galaxy+'/'+galaxy+'_'+line

degas.calscans(dataFileName, start=47, stop=82, refscans=[45],outdir=dataOutDir)
WARNING: Can not find data for scan 47 window 0 feed 10 polarization 0
Now Processing Scan 47 for Feed 12                                    
Now Processing Scan 48 for Feed 12                                    
Now Processing Scan 49 for Feed 12                                    
Now Processing Scan 50 for Feed 12                                    
Now Processing Scan 51 for Feed 12                                    
Now Processing Scan 52 for Feed 12                                    
Now Processing Scan 53 for Feed 12            
<snip>

Now Processing Scan 142 for Feed 14
Now Processing Scan 143 for Feed 14
WARNING: Can not find data for scan 99 window 0 feed 11 polarization 0
Now Processing Scan 99 for Feed 13
Now Processing Scan 100 for Feed 13
Now Processing Scan 101 for Feed 13
Now Processing Scan 102 for Feed 13
Now Processing Scan 103 for Feed 13
Now Processing Scan 104 for Feed 13
```

**Comment by low-sky** [comment] 2017-02-23 16:51
I believe this is "functioning as intended" in that the filler has put in a dummy scan for feed 11 into the SDFITS file even though there are no valid spectra there.  However, it would be good to verify this, which I will do on the next major pass through the issues.

**Comment by low-sky** [comment] 2017-08-15 01:41
I've confirmed this is harmless.   The `sdfits` filler writes dummy data for the occasional feed to two separate sdfits file in the VEGAS dump.  For example, the file for bank A has the feed 10 data, but the error is being thrown when the data are processing file E which holds feeds 12 and 14.  I'm closing this now and hope that this doesn't end up concealing a bigger, actual issue later on.

**Closed** 2017-08-15 01:41 UTC
